### PR TITLE
Fix NPE when walking a missing node that will have missing properties

### LINKED ISSUE #1151: NPE during JSON schema walk with validation
We ran into this while migrating to 1.5.5. A JSON schema walk returned an NPE rather than returning validation messages while validating a YAML document that did not have the corresponding properties. Below is the smallest recreate I've found that still fails with an NPE. I've replaced the YAML nodes with an instance of the MissingNode below to simulate the missing object properties.

```java
import com.fasterxml.jackson.databind.node.MissingNode;
import com.networknt.schema.JsonSchema;
import com.networknt.schema.JsonSchemaFactory;
import com.networknt.schema.SpecVersion;

public class SchemaTest {

    public static void main(String[] args) {
        String schemaContents = """
            {
                "type": "object",
                "properties": {
                    "field": {
                    "anyOf": [
                        {
                        "type": "string"
                        }
                    ]
                    }
                }
            }
            """;

        JsonSchemaFactory factory = JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V7);
        JsonSchema schema = factory.getSchema(schemaContents);
        schema.walk(MissingNode.getInstance(), true).getValidationMessages();
    }
}
```

Stack trace:
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.getNodeType()" because "node" is null
        at com.networknt.schema.TypeFactory.getValueNodeType(TypeFactory.java:78)
        at com.networknt.schema.utils.JsonNodeUtil.equalsToSchemaType(JsonNodeUtil.java:70)
        at com.networknt.schema.TypeValidator.equalsToSchemaType(TypeValidator.java:50)
        at com.networknt.schema.AnyOfValidator.validate(AnyOfValidator.java:84)
        at com.networknt.schema.AnyOfValidator.walk(AnyOfValidator.java:166)
        at com.networknt.schema.JsonSchema.walk(JsonSchema.java:1278)
        at com.networknt.schema.PropertiesValidator.walkSchema(PropertiesValidator.java:197)
        at com.networknt.schema.PropertiesValidator.validate(PropertiesValidator.java:109)
        at com.networknt.schema.PropertiesValidator.walk(PropertiesValidator.java:133)
        at com.networknt.schema.JsonSchema.walk(JsonSchema.java:1278)
        at com.networknt.schema.JsonSchema.walkAtNodeInternal(JsonSchema.java:1247)
        at com.networknt.schema.JsonSchema.walk(JsonSchema.java:1082)
        at com.networknt.schema.JsonSchema.walk(JsonSchema.java:1162)
       ...
```

### PR DESCRIPTION
**Pull request by justin-tay**
Closes #1151 

Fixes the NPE by having `TypeFactory.getValueNodeType((JsonNode node, SchemaValidatorsConfig config)` handle the case where a `null` was passed in as the node.

I had considered if it should be ensured that the node inputs should always be non null and always replace `null` by `MissingNode` instead. For instance having `PropertiesValidator` set the input as `MissingNode` instead of `null`. But since `JsonNode.get(String fieldName)` returns `null` for missing nodes I wasn't sure it would be appropriate.

### CODE REVIEW

File: src/test/java/com/networknt/schema/JsonWalkTest.java [hunk 1]
```diff
@@ -110,6 +111,26 @@ void testWalkWithDifferentListeners() throws IOException {
...
+                + "                        \"type\": \"string\"\n"
+                + "                        }\n"
+                + "                    ]\n"
+                + "                    }\n"
+                + "                }\n"
+                + "            }";
+
+        JsonSchemaFactory factory = JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V7);
+        JsonSchema schema = factory.getSchema(schemaContents);
+        schema.walk(MissingNode.getInstance(), true).getValidationMessages();
```
Comment (jkosternl) [inline src/test/java/com/networknt/schema/JsonWalkTest.java:131]: Perhaps assert any valid response from the walk method, or otherwise `assertNonNull`?

File: src/main/java/com/networknt/schema/TypeFactory.java [hunk 2]
```diff
@@ -75,6 +75,11 @@ public static JsonType getSchemaNodeType(JsonNode node) {
      * @return the json type
      */
     public static JsonType getValueNodeType(JsonNode node, SchemaValidatorsConfig config) {
+        if (node == null) {
+            // This returns JsonType.UNKNOWN to be consistent with the behavior when
```
Comment (jkosternl) [inline src/main/java/com/networknt/schema/TypeFactory.java:79]:
```suggestion
            // JsonType.UNKNOWN is consistent with JsonNodeType.MISSING
```
Trying to make it a bit concise?

**Review by jkosternl — COMMENTED** [review]
Just 2 minor remarks, to take into consideration. Good job!

**Review by stevehu — APPROVED** [review]

File: src/main/java/com/networknt/schema/TypeFactory.java (hunk 2 above)
Comment (jkosternl) [reply src/main/java/com/networknt/schema/TypeFactory.java:79]: Resolved without any update, somehow?

Comment (justin-tay) [reply src/main/java/com/networknt/schema/TypeFactory.java:79]: Thanks for the suggestion. However your suggestion doesn't convey the intent of the comment that the return result should match the result in the later switch statement for missing node.

Comment (jkosternl) [reply src/main/java/com/networknt/schema/TypeFactory.java:79]: Ah I see, thanks for your response 👍🏻 .

**Comment by stevehu** [comment]
@justin-tay The latest commit is not included in the previous PR which is merged so quickly. Could you please submit another PR to include the test case? Thanks.

**Comment by justin-tay** [comment]
@stevehu It looks like the latest commit to add the `assertDoesNotThrow` was included in the merged commit https://github.com/networknt/json-schema-validator/commit/da3865cb4b4155e4321c48998018634c32ce859d so there's nothing more. Thanks!
